name: Label Issues

on:
  issues:
    types: [opened, reopened]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/label-pr.yml'
